name: Testing Express Ap

on:
  push:
    bracnhes: 
      - main
  pull_request:
    bracnhes: 
      - main



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 21.6.2

      - name: Install 
        run: npm install

      - name: Test
        run: npm run test

      