name: Testing Express Ap

on:
  push:
    bracnhes: 
      - main
  pull_request:
    bracnhes: 
      - main



jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [21.6.2, 22.0]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup Node ${{matrix.node_version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node_version}}

      - name: Install 
        run: npm install

      - name: Test
        run: npm run test

      